# permissions to do viewer clusters.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: cluster-viewer-role
rules:
- apiGroups:
  - kubevirt.cluster.x-k8s.io
  resources:
  - clusters
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - kubevirt.cluster.x-k8s.io
  resources:
  - clusters/status
  verbs:
  - get
