# permissions to do viewer machines.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: machine-viewer-role
rules:
- apiGroups:
  - kubevirt.cluster.x-k8s.io
  resources:
  - machines
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - kubevirt.cluster.x-k8s.io
  resources:
  - machines/status
  verbs:
  - get
